### ISSUE TITLE
[DevExp] Avoid dirty git builds to be deployed to specific environments

### ISSUE THREAD

**Issue by kristofmartens** [datamindedbe/datafy-roadmap#28] opened 2021-09-21 15:14 UTC
Right now there is nothing preventing people to deploy code with local customisations that are not stored in git repositories to production environments. We have seen that some developers actually have done this and we had no idea how to fix their code once he left on holidays. 
Of course not for all environments as during development you want to be able to have a fast iteration cycle.

**Comment by stijndehaes** [comment] 2021-09-24 09:17
Duplicate of: https://github.com/datamindedbe/datafy-roadmap/issues/27
Also please follow our issue template the next time, thank you!

**Closed by stijndehaes** 2021-09-24 09:17 UTC
Labels: enhancement, dev expierence
